import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:uuid/uuid.dart';
import '../domain/product.dart';
import '../domain/category.dart';

part 'inventory_repository.g.dart';

@Riverpod(keepAlive: true)
InventoryRepository inventoryRepository(Ref ref) {
  return InventoryRepository(
    FirebaseFirestore.instance,
    FirebaseStorage.instance,
  );
}

@riverpod
Stream<List<Product>> productsStream(Ref ref) {
  return ref.watch(inventoryRepositoryProvider).processProductsStream();
}

@riverpod
Stream<List<Category>> categoriesStream(Ref ref) {
  return ref.watch(inventoryRepositoryProvider).getCategoriesStream();
}

class InventoryRepository {
  final FirebaseFirestore _firestore;
  final FirebaseStorage _storage;

  InventoryRepository(this._firestore, this._storage);

  CollectionReference get _productsRef => _firestore.collection('products');

  Stream<List<Product>> processProductsStream() {
    return _productsRef.orderBy('createdAt', descending: true).snapshots().map((
      snapshot,
    ) {
      return snapshot.docs.map((doc) => Product.fromFirestore(doc)).toList();
    });
  }

  Future<void> addProduct(Product product, File? imageFile) async {
    String? imageUrl;
    if (imageFile != null) {
      final ref = _storage.ref().child(
        'product_images/${const Uuid().v4()}.jpg',
      );
      await ref.putFile(imageFile);
      imageUrl = await ref.getDownloadURL();
    }

    final newProduct = product.copyWith(
      imagePath: imageUrl,
      createdAt: DateTime.now(),
    );

    // Convert to map without ID (autogenerated)
    await _productsRef.add(newProduct.toFirestore());
  }

  Future<void> updateProduct(Product product, File? newImageFile) async {
    String? imageUrl = product.imagePath;
    if (newImageFile != null) {
      final ref = _storage.ref().child(
        'product_images/${const Uuid().v4()}.jpg',
      );
      await ref.putFile(newImageFile);
      imageUrl = await ref.getDownloadURL();
    }

    await _productsRef
        .doc(product.id)
        .update(product.copyWith(imagePath: imageUrl).toFirestore());
  }

  Future<void> deleteProduct(String productId) async {
    await _productsRef.doc(productId).delete();
  }

  // Categories
  CollectionReference get _categoriesRef => _firestore.collection('categories');

  Stream<List<Category>> getCategoriesStream() {
    return _categoriesRef.orderBy('name').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => Category.fromFirestore(doc)).toList();
    });
  }

  Future<void> addCategory(String name) async {
    await _categoriesRef.add({'name': name});
  }
}
